Repository honey-team/ufpy, pull requests merged in 2024-06, with the labels that each got.

#3 UDict + cmp_generator
  examples/.md
  examples/udict.md
  tests/test_udict.py
  ufpy/__init__.py
  ufpy/cmp.py
  ufpy/math_op.py
  ufpy/typ/__init__.py
  ufpy/typ/protocols.py
  ufpy/typ/type_alias.py
  ufpy/udict.py
  ufpy/utils.py
Labels: new feature, new class, new function

#20 Add import of `future.annotations` for simplifying of code with string annotations
  ufpy/udict.py
Labels: invalid

#22 fix sourcery's suggestions
  tests/test_udict.py
  ufpy/udict.py
Labels: bug, invalid

#11 UStack
  examples/ustack.md
  tests/test_ustack.py
  ufpy/__init__.py
  ufpy/typ/protocols.py
  ufpy/typ/type_alias.py
  ufpy/ustack.py
Labels: new feature, new class, new variable, good first pull

#14 Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: github

#25 Init docs site
  .readthedocs.yaml
  docs/generators.md
  docs/index.md
  docs/requirements.txt
  docs/source/conf.py
  docs/source/index.md
  docs/type_checking/protocols.md
  docs/type_checking/type_alias.md
  docs/useful_classes/udict.md
  docs/useful_classes/ustack.md
  mkdocs.yml
Labels: documentation

#32 bug fix packaging + fix printing with deletion of `str()`
  .gitignore
  examples/udict.md
  setup.py
  tests/test_udict.py
  ufpy/__init__.py
  ufpy/typ/__init__.py
  ufpy/typ/type_alias.py
  ufpy/udict.py
  ufpy/ustack.py
  ufpy/utils.py
  upload_testpypi.bat
Labels: bug

#37 UGithubDownloader + some functions and methods for downloading files and folders from repo or downloading all repo.
  examples/github/.assets/download1.png
  examples/github/.assets/download2.png
  examples/github/.assets/download3.png
  examples/github/.assets/download4.png
  examples/github/.assets/download5.png
  examples/github/download.md
  requirements.txt
  setup.py
  ufpy/__init__.py
  ufpy/github/__init__.py
  ufpy/github/download.py
  ufpy/path/__init__.py
  ufpy/path/files.py
  ufpy/path/tools.py
Labels: new feature, new class, new function
